### ISSUE TITLE
Long popup text strings need better treatment

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv-ui#31]
Currently long strings in popup data can't be read.   There is often important information in these strings.  At a minimum mousing over a string should display the full value.

Also, when mousing over a string a hypertext style finger pointer appears, at least in chrome, but clicking it does nothing.  Unless the string is a hpyerlink we probably shouldn't do that.  Adds to the frustration of not being able to see the string.

<img width="308" alt="Screen Shot 2020-10-09 at 11 23 05 PM" src="https://user-images.githubusercontent.com/933148/95647774-ddeb1a80-0a86-11eb-8003-9ceeb2ceee55.png">

**Comment by turner** [comment]
Closed with 05a382f
