### ISSUE TITLE
npm installation fails

### ISSUE THREAD

**Issue by adadiehl** [igvteam/igv-ui#41]
npm install https://github.com/igvteam/igv-ui.git
npm ERR! code 128
npm ERR! command failed
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/igvteam/igv-ui.git
npm ERR! command-line line 0: unsupported option "accept-new".
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm -v
7.17.0
node -v
v14.17.1

**Comment by jrobinso** [comment]
igv-ui is not an NPM module, it is a component for the igv.js project and not designed to be used stand-alone.   What are you hoping to do with it?

**Comment by adadiehl** [comment]
Encountered this error trying to install igv via 'node install igv' --
attempted node install from the igv-ui git repository when this failed.
Posted the error here because the issue is directly with igv-ui
installation, not igv installation.

-A

**Comment by jrobinso** [comment]
I don't know what "node install" does.   'npm install igv' works for me.

**Comment by adadiehl** [comment]
Sorry, npm install

**Comment by adadiehl** [comment]
Based on the error message, seems to be a permissions issue. Likely works
for you because you have dev permissions on the repository. Original error
message appeared to have some potentially useful information to resolve the
problem.

**Comment by jrobinso** [comment]
It runs on every commit via github workflow, and we have ~4,000 NPM installs weekly from organizations other than ourselves.

**Comment by jrobinso** [comment]
So its a puzzle.

**Comment by adadiehl** [comment]
Indeed. Good news is I managed to work around the issue by linking directly
to the codebase in my index.html. Guess it's going to be included on all
pages instead of just where it's needed. Oh well...

**Comment by jrobinso** [comment]
I have also had weird errors installing packages from github.  I have on my to-do list just to put these dependent projects in NPM,  I think that will solve this sort of error permanently.    This one is especially strange as we are both on the same node and NPM versions.   You might track clearing your NPM cache.

**Comment by adadiehl** [comment]
Unfortunately, clearing the npm cache didn't do the trick. Based on what
you're saying, I'm probably a weird edge case. However, I was able to get
around it by linking to the scripts, so I'm good to go -- well, almost...

That said, since I have you on the line, so to speak, I hope you don't mind
if I run another issue past you. This one seems likely to be an issue with
my implementation, not the igv.js code base, so probably not appropriate to
open a new issue!

I'm putting together a tool for viewing aligned plasmid sequences, where
the reference is a fasta file describing the plasmid sequence and the
single track is the bam file of reads aligned to the plasmid file. Fasta
references and bam files are stored in a tmp folder on our server and
retrieved with an api call. I've verified the api calls are returning the
correct files, but am hitting a brick wall when I try to load a reference
into a new igv.js instance. Looks as if the chromosome names are not being
parsed out when the fasta file is loaded, but I can't quite tell why based
on the igv.js code.  Attaching a representative fasta file, code for
invoking the igv session, and the stack trace. I've also tried indexing
with faidx and including the indexURL param in the reference block and am
getting similar errors.

Hoping you can spot the problem and point me in the right direction.

Thank you for all your help!

Best Regards,
Adam Diehl

class ResultsDisplay extends Component {

    // initialize our state


    constructor(props) {

        super(props);

        this.state = {

            serverId: 7573260109,

            refFile: "dp104_p4_2xSymmetricLacO_0_reference.fasta",

            algnFile: "filtered_alignment.bam"

        };

    }


    componentDidMount() {

        const igvDiv = document.getElementById("igv-div");

        let options =

            {

                reference: {

                    "name": this.state.refFile,

                    "fastaURL": browser.apiAddr + '/getResult?serverId=' +
this.state.serverId + "&fileName=" + this.state.refFile,

                    "indexed": false

                },

                tracks: [

                    {

                        "name": "Alignment",

                        "url": browser.apiAddr + '/getResult?serverId=' +
this.state.serverId + "&fileName=" + this.state.algnFile,

                        "format": "bam"

                    }

                ]

            };

        igv.createBrowser(igvDiv, options)

        .then(function (browser) {

            console.log("Created IGV browser");

        });

    }


    componentWillUnmount() {

        // Clean up our area.


    }



    // Render the UI.


    render() {

        return (

                <div id="igv-div">

                </div>

        );

    }

}

Uncaught (in promise) TypeError: Cannot read property 'startsWith' of
undefined
    at genome.js:172
    at Array.forEach (<anonymous>)
    at new Uo (genome.js:171)
    at Object.loadGenome (genome.js:57)
    at async Hu.loadReference (browser.js:607)
    at async Hu.loadSessionObject (browser.js:501)
    at async Object.createBrowser (igv-create.js:74)

**Comment by jrobinso** [comment]
Most likely,  this is not returning what you think it is.  I have no way to verify that of course.   Try pasting that URL into a web browser and see what's returned.

browser.apiAddr + '/getResult?serverId=' + this.state.serverId + "&fileName=" + this.state.refFile,

**Comment by jrobinso** [comment]
A more direct test is to observe the network traffic using your browsers developement tools.   The response should be the content of the fasta file.

**Comment by adadiehl** [comment]
You were correct: my function was returning json instead of just the fasta
file. It's working now with that resolved. Thank you again for your help!

Adam

**Comment by Al-Mclean** [comment]
Hi @adadiehl, I'm having the same issue to your original post with a different install (homebridge-broadlink-rm plug-in) - could you provide a bit more detail on how you worked around the issue?

Thanks,

Al

**Comment by adadiehl** [comment]
Hi Al,

I was unable to resolve the issue with npm and ended up linking to the
source code directly within index.html for the app I'm developing, as
described on the github README (https://github.com/igvteam/igv.js). Hope
this helps!

Best,
Adam Diehl

**Comment by jrobinso** [comment]
I've never been able to reproduce the original problem.   ```npm install igv``` works beautifully for me.  This particular project (igv-ui) is not an npm module, and really not designed for general use outside of the igv projects but if it works for you great.

**Comment by adadiehl** [comment]
As mentioned before, the issue crops up in the course of a normal npm
install of igv.js. The cause of that failure traced to the failure to
install igv-ui as a dependency. The attempts to install igv-ui as a
standalone were solely meant to address this issue, since, in my
experience, installing the underlying (failed) dependencies often fixes npm
install problems. This is not the case for igv-ui, unfortunately. I am
sorry if the original issue submission was unclear in this regard.

That said, linking to the code works beautifully. Just be aware that
installation of the whole package will fail as a result of this limitation
in some (likely isolated) cases. It may be worth adding a warning somewhere
in the installation docs with a recommendation to link to the source code
in cases of installation failure. This might save us all some time in
future.

Cheers,
Adam Diehl

**Comment by jrobinso** [comment]
@adadiehl If I knew what the "isolated cases" were I could add a warning, but more likely I would fix them.   We have automated builds, on multiple platforms,  and something on the order of 10,000 installations, so whatever causes this is rare.

**Comment by jrobinso** [comment]
A key question here is why is your build system trying to install igv-ui in the first place?  Its not part of the igv.js distribution, all required packages are rolled up in igv.esm.js.

**Comment by jrobinso** [comment]
OK I don't know why you can't install igv-ui, perhaps your build or package manager can't install from github or there is some issue with our configuration, but the project is not needed at runtime so I moved the dependency to "dev-dependencies", which is probably where it belongs anyway.   This might fix the problem, certainly it should prevent attempts to install igv-ui from an "igv" install.
