### ISSUE TITLE
Alert Dialog suggestion

### ISSUE THREAD

**Issue by rootux** [igvteam/igv-ui#43]
First. Thank you for this powerful library.

Second,
Inside Alert dialog present() method there is a call to  .focus can lead to an unwanted page scroll 

For example, if we embed `igv` as part of a larger system. In that case, we want to be able to control if focusing (and especially scrolling) happens.

.focus have an attribute of should scroll which is true by default.

.[here](https://github.com/igvteam/igv-ui/blob/19108bc19ff347dcceb2f053dc63ab05b9af247d/js/components/alertDialog.js#L88) 

Would you accept a PR that include options to disableFocus or to disableScrolling? This can be as part of the `alert` attribute

**Comment by jrobinso** [comment]
Sure we will consider a PR, or fix this in some other way.  I have to warn you though that response might be slow for the next few weeks.
